### ISSUE TITLE
xUnit 2?

### ISSUE THREAD

**Issue by luckeeben** [giggio/xunit-retry#2]
Hi, are you planning to support xUnit 2?
Thanks

**Comment by donbavand** [comment]
Hi @giggio any movement on this? This would be really handy for our project.

**Comment by giggio** [comment]
I am quite busy, a PR is welcome.

**Comment by RajaBellebon** [comment]
Hello @giggio , 

so the release 2.0 is coming soon as stated in the PR. Do you know if this release will cover Xunit 2.1? 

Regards,

Raja

**Comment by giggio** [comment]
@RajaBellebon Yes, the PR covers 2.1, you can see the changes in the `package.config` file.

**Comment by RajaBellebon** [comment]
@giggio , 

Thanks for your answer!

Waiting for the PR to be merged!

Grazie Mille,

**Comment by pratikvadwala** [comment]
Hey @RajaBellebon,

looks like xunit 2.0 is out. https://www.nuget.org/packages/XunitRetry/

Regards,
Pratik

**Comment by jonparky** [comment]
Not been able to get this working ... has anyone else ?

**Comment by giggio** [comment]
Closed on #3.
